import process from 'node:process'
import { defineConfig } from 'vite'
import { tanstackStart } from '@tanstack/react-start/plugin/vite'
import viteReact from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
const previewBase = process.env.PREVIEW_BASE || '/'
const isPreview = process.env.PREVIEW_STATIC === '1'

// TanStack Start (Vite-based) with SSR on every route.
// Route tree is generated by the Start plugin from src/routes into
// src/routeTree.gen.ts (gitignored). Tailwind v4 runs via its Vite plugin,
// so there is no PostCSS config and no `tailwindcss` PostCSS plugin.
// The "~/*" path alias is resolved natively by Vite via resolve.tsconfigPaths.
export default defineConfig({
  base: previewBase,
  define: { 'import.meta.env.PREVIEW_STATIC': JSON.stringify(isPreview) },
  server: {
    port: 3000,
    // Quick Tunnel hostnames rotate; allow them for private previews.
    allowedHosts: ['.trycloudflare.com', 'localhost', '127.0.0.1'],
  },
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [
    // Tailwind v4 must run before the React plugin.
    tailwindcss(),
    // TanStack Start: SSR, router codegen, server functions. Defaults point at
    // src/router.tsx, src/routes, src/server.ts, src/client.tsx.
    tanstackStart(isPreview ? {
      router: { basepath: previewBase.replace(/\/$/, '') },
      prerender: { enabled: true, autoStaticPathsDiscovery: false, crawlLinks: true, concurrency: 4, failOnError: true, filter: ({ path }) => !path.includes("?") },
      pages: ['en', 'da', 'ar'].map(locale => ({ path: `/${locale}` })),
    } : {}),
    viteReact(),
  ],
})
